import React from "react";
import type { Metadata } from 'next'
import './globals.css'

import { Provider } from "@/components/provider-theme"
import { Footer } from "@/components/footer"
import {Nav} from "@/components/nav";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';

import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"

export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
        <html lang="en" suppressHydrationWarning>
            <head>
                <title>Zuendorf.Me</title>
                <meta property="og:title" content="Zuendorf.Me" key="title"/>
            </head>
            <body className={cn(
                "h-full bg-background font-sans antialiased",
                fontSans.variable
            )}
            >
            <Provider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                <Nav/>
                <main
                    className={cn("container mx-auto grow place-items-center w-full md:w-10/12 xl:w-8/12")}>{children}</main>
                <Footer/>
            </Provider>
            <SpeedInsights/>
            <Analytics/>
            </body>
        </html>
      </>
    )
}
