/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import { relations, sql } from '@payloadcms/db-postgres/drizzle';
import {
  boolean,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  serial,
  timestamp,
  uniqueIndex,
  varchar
} from '@payloadcms/db-postgres/drizzle/pg-core';
export const enum_tag_type = pgEnum('enum_tag_type', ['techstack', 'skill', 'socials', 'other']);
export const enum_projects_status = pgEnum('enum_projects_status', ['draft', 'published']);
export const enum__projects_v_version_status = pgEnum('enum__projects_v_version_status', [
  'draft',
  'published'
]);

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    caption: jsonb('caption'),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width'),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height'),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize'),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_square_url: varchar('sizes_square_url'),
    sizes_square_width: numeric('sizes_square_width'),
    sizes_square_height: numeric('sizes_square_height'),
    sizes_square_mimeType: varchar('sizes_square_mime_type'),
    sizes_square_filesize: numeric('sizes_square_filesize'),
    sizes_square_filename: varchar('sizes_square_filename'),
    sizes_small_url: varchar('sizes_small_url'),
    sizes_small_width: numeric('sizes_small_width'),
    sizes_small_height: numeric('sizes_small_height'),
    sizes_small_mimeType: varchar('sizes_small_mime_type'),
    sizes_small_filesize: numeric('sizes_small_filesize'),
    sizes_small_filename: varchar('sizes_small_filename'),
    sizes_medium_url: varchar('sizes_medium_url'),
    sizes_medium_width: numeric('sizes_medium_width'),
    sizes_medium_height: numeric('sizes_medium_height'),
    sizes_medium_mimeType: varchar('sizes_medium_mime_type'),
    sizes_medium_filesize: numeric('sizes_medium_filesize'),
    sizes_medium_filename: varchar('sizes_medium_filename'),
    sizes_large_url: varchar('sizes_large_url'),
    sizes_large_width: numeric('sizes_large_width'),
    sizes_large_height: numeric('sizes_large_height'),
    sizes_large_mimeType: varchar('sizes_large_mime_type'),
    sizes_large_filesize: numeric('sizes_large_filesize'),
    sizes_large_filename: varchar('sizes_large_filename'),
    sizes_xlarge_url: varchar('sizes_xlarge_url'),
    sizes_xlarge_width: numeric('sizes_xlarge_width'),
    sizes_xlarge_height: numeric('sizes_xlarge_height'),
    sizes_xlarge_mimeType: varchar('sizes_xlarge_mime_type'),
    sizes_xlarge_filesize: numeric('sizes_xlarge_filesize'),
    sizes_xlarge_filename: varchar('sizes_xlarge_filename'),
    sizes_og_url: varchar('sizes_og_url'),
    sizes_og_width: numeric('sizes_og_width'),
    sizes_og_height: numeric('sizes_og_height'),
    sizes_og_mimeType: varchar('sizes_og_mime_type'),
    sizes_og_filesize: numeric('sizes_og_filesize'),
    sizes_og_filename: varchar('sizes_og_filename')
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
    media_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      'media_sizes_thumbnail_sizes_thumbnail_filename_idx'
    ).on(columns.sizes_thumbnail_filename),
    media_sizes_square_sizes_square_filename_idx: index(
      'media_sizes_square_sizes_square_filename_idx'
    ).on(columns.sizes_square_filename),
    media_sizes_small_sizes_small_filename_idx: index(
      'media_sizes_small_sizes_small_filename_idx'
    ).on(columns.sizes_small_filename),
    media_sizes_medium_sizes_medium_filename_idx: index(
      'media_sizes_medium_sizes_medium_filename_idx'
    ).on(columns.sizes_medium_filename),
    media_sizes_large_sizes_large_filename_idx: index(
      'media_sizes_large_sizes_large_filename_idx'
    ).on(columns.sizes_large_filename),
    media_sizes_xlarge_sizes_xlarge_filename_idx: index(
      'media_sizes_xlarge_sizes_xlarge_filename_idx'
    ).on(columns.sizes_xlarge_filename),
    media_sizes_og_sizes_og_filename_idx: index('media_sizes_og_sizes_og_filename_idx').on(
      columns.sizes_og_filename
    )
  })
);

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 })
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email)
  })
);

export const tag = pgTable(
  'tag',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    type: enum_tag_type('type').notNull(),
    link: varchar('link'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull()
  },
  (columns) => ({
    tag_updated_at_idx: index('tag_updated_at_idx').on(columns.updatedAt),
    tag_created_at_idx: index('tag_created_at_idx').on(columns.createdAt)
  })
);

export const experiences = pgTable(
  'experiences',
  {
    id: serial('id').primaryKey(),
    company: varchar('company').notNull(),
    position: varchar('position').notNull(),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }).notNull(),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    description: varchar('description'),
    responsibilityOne: varchar('responsibility_one').notNull(),
    responsibilityTwo: varchar('responsibility_two'),
    responsibilityThree: varchar('responsibility_three'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y')
  },
  (columns) => ({
    experiences_updated_at_idx: index('experiences_updated_at_idx').on(columns.updatedAt),
    experiences_created_at_idx: index('experiences_created_at_idx').on(columns.createdAt),
    experiences_filename_idx: uniqueIndex('experiences_filename_idx').on(columns.filename)
  })
);

export const experiences_rels = pgTable(
  'experiences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagID: integer('tag_id')
  },
  (columns) => ({
    order: index('experiences_rels_order_idx').on(columns.order),
    parentIdx: index('experiences_rels_parent_idx').on(columns.parent),
    pathIdx: index('experiences_rels_path_idx').on(columns.path),
    experiences_rels_tag_id_idx: index('experiences_rels_tag_id_idx').on(columns.tagID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [experiences.id],
      name: 'experiences_rels_parent_fk'
    }).onDelete('cascade'),
    tagIdFk: foreignKey({
      columns: [columns['tagID']],
      foreignColumns: [tag.id],
      name: 'experiences_rels_tag_fk'
    }).onDelete('cascade')
  })
);

export const projects = pgTable(
  'projects',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    shortDescription: varchar('short_description'),
    slug: varchar('slug'),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null'
    }),
    content: jsonb('content'),
    liveUrl: varchar('live_url'),
    repoUrl: varchar('repo_url'),
    meta_title: varchar('meta_title'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null'
    }),
    meta_description: varchar('meta_description'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_projects_status('_status').default('draft')
  },
  (columns) => ({
    projects_slug_idx: index('projects_slug_idx').on(columns.slug),
    projects_hero_image_idx: index('projects_hero_image_idx').on(columns.heroImage),
    projects_meta_meta_image_idx: index('projects_meta_meta_image_idx').on(columns.meta_image),
    projects_updated_at_idx: index('projects_updated_at_idx').on(columns.updatedAt),
    projects_created_at_idx: index('projects_created_at_idx').on(columns.createdAt),
    projects__status_idx: index('projects__status_idx').on(columns._status)
  })
);

export const projects_rels = pgTable(
  'projects_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagID: integer('tag_id')
  },
  (columns) => ({
    order: index('projects_rels_order_idx').on(columns.order),
    parentIdx: index('projects_rels_parent_idx').on(columns.parent),
    pathIdx: index('projects_rels_path_idx').on(columns.path),
    projects_rels_tag_id_idx: index('projects_rels_tag_id_idx').on(columns.tagID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [projects.id],
      name: 'projects_rels_parent_fk'
    }).onDelete('cascade'),
    tagIdFk: foreignKey({
      columns: [columns['tagID']],
      foreignColumns: [tag.id],
      name: 'projects_rels_tag_fk'
    }).onDelete('cascade')
  })
);

export const _projects_v = pgTable(
  '_projects_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => projects.id, {
      onDelete: 'set null'
    }),
    version_title: varchar('version_title'),
    version_shortDescription: varchar('version_short_description'),
    version_slug: varchar('version_slug'),
    version_heroImage: integer('version_hero_image_id').references(() => media.id, {
      onDelete: 'set null'
    }),
    version_content: jsonb('version_content'),
    version_liveUrl: varchar('version_live_url'),
    version_repoUrl: varchar('version_repo_url'),
    version_meta_title: varchar('version_meta_title'),
    version_meta_image: integer('version_meta_image_id').references(() => media.id, {
      onDelete: 'set null'
    }),
    version_meta_description: varchar('version_meta_description'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3
    }),
    version__status: enum__projects_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave')
  },
  (columns) => ({
    _projects_v_parent_idx: index('_projects_v_parent_idx').on(columns.parent),
    _projects_v_version_version_slug_idx: index('_projects_v_version_version_slug_idx').on(
      columns.version_slug
    ),
    _projects_v_version_version_hero_image_idx: index(
      '_projects_v_version_version_hero_image_idx'
    ).on(columns.version_heroImage),
    _projects_v_version_meta_version_meta_image_idx: index(
      '_projects_v_version_meta_version_meta_image_idx'
    ).on(columns.version_meta_image),
    _projects_v_version_version_updated_at_idx: index(
      '_projects_v_version_version_updated_at_idx'
    ).on(columns.version_updatedAt),
    _projects_v_version_version_created_at_idx: index(
      '_projects_v_version_version_created_at_idx'
    ).on(columns.version_createdAt),
    _projects_v_version_version__status_idx: index('_projects_v_version_version__status_idx').on(
      columns.version__status
    ),
    _projects_v_created_at_idx: index('_projects_v_created_at_idx').on(columns.createdAt),
    _projects_v_updated_at_idx: index('_projects_v_updated_at_idx').on(columns.updatedAt),
    _projects_v_latest_idx: index('_projects_v_latest_idx').on(columns.latest),
    _projects_v_autosave_idx: index('_projects_v_autosave_idx').on(columns.autosave)
  })
);

export const _projects_v_rels = pgTable(
  '_projects_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagID: integer('tag_id')
  },
  (columns) => ({
    order: index('_projects_v_rels_order_idx').on(columns.order),
    parentIdx: index('_projects_v_rels_parent_idx').on(columns.parent),
    pathIdx: index('_projects_v_rels_path_idx').on(columns.path),
    _projects_v_rels_tag_id_idx: index('_projects_v_rels_tag_id_idx').on(columns.tagID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_projects_v.id],
      name: '_projects_v_rels_parent_fk'
    }).onDelete('cascade'),
    tagIdFk: foreignKey({
      columns: [columns['tagID']],
      foreignColumns: [tag.id],
      name: '_projects_v_rels_tag_fk'
    }).onDelete('cascade')
  })
);

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull()
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt
    )
  })
);

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
    usersID: integer('users_id'),
    tagID: integer('tag_id'),
    experiencesID: integer('experiences_id'),
    projectsID: integer('projects_id')
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx'
    ).on(columns.mediaID),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx'
    ).on(columns.usersID),
    payload_locked_documents_rels_tag_id_idx: index('payload_locked_documents_rels_tag_id_idx').on(
      columns.tagID
    ),
    payload_locked_documents_rels_experiences_id_idx: index(
      'payload_locked_documents_rels_experiences_id_idx'
    ).on(columns.experiencesID),
    payload_locked_documents_rels_projects_id_idx: index(
      'payload_locked_documents_rels_projects_id_idx'
    ).on(columns.projectsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk'
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'),
    tagIdFk: foreignKey({
      columns: [columns['tagID']],
      foreignColumns: [tag.id],
      name: 'payload_locked_documents_rels_tag_fk'
    }).onDelete('cascade'),
    experiencesIdFk: foreignKey({
      columns: [columns['experiencesID']],
      foreignColumns: [experiences.id],
      name: 'payload_locked_documents_rels_experiences_fk'
    }).onDelete('cascade'),
    projectsIdFk: foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'payload_locked_documents_rels_projects_fk'
    }).onDelete('cascade')
  })
);

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull()
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt
    )
  })
);

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id')
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade')
  })
);

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull()
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt
    )
  })
);

export const section_content_quick_skills = pgTable(
  'section_content_quick_skills',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    skill: varchar('skill').notNull()
  },
  (columns) => ({
    _orderIdx: index('section_content_quick_skills_order_idx').on(columns._order),
    _parentIDIdx: index('section_content_quick_skills_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [section_content.id],
      name: 'section_content_quick_skills_parent_id_fk'
    }).onDelete('cascade')
  })
);

export const section_content = pgTable(
  'section_content',
  {
    id: serial('id').primaryKey(),
    MainIntroSection: jsonb('main_intro_section').notNull(),
    MainAboutMeSection: jsonb('main_about_me_section').notNull(),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null'
    }),
    selectedProjects: integer('selected_projects_id').references(() => projects.id, {
      onDelete: 'set null'
    }),
    selectedExperiences: integer('selected_experiences_id').references(() => experiences.id, {
      onDelete: 'set null'
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
  },
  (columns) => ({
    section_content_avatar_idx: index('section_content_avatar_idx').on(columns.avatar),
    section_content_selected_projects_idx: index('section_content_selected_projects_idx').on(
      columns.selectedProjects
    ),
    section_content_selected_experiences_idx: index('section_content_selected_experiences_idx').on(
      columns.selectedExperiences
    )
  })
);

export const section_content_rels = pgTable(
  'section_content_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagID: integer('tag_id')
  },
  (columns) => ({
    order: index('section_content_rels_order_idx').on(columns.order),
    parentIdx: index('section_content_rels_parent_idx').on(columns.parent),
    pathIdx: index('section_content_rels_path_idx').on(columns.path),
    section_content_rels_tag_id_idx: index('section_content_rels_tag_id_idx').on(columns.tagID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [section_content.id],
      name: 'section_content_rels_parent_fk'
    }).onDelete('cascade'),
    tagIdFk: foreignKey({
      columns: [columns['tagID']],
      foreignColumns: [tag.id],
      name: 'section_content_rels_tag_fk'
    }).onDelete('cascade')
  })
);

export const legal_content = pgTable('legal_content', {
  id: serial('id').primaryKey(),
  englishText: jsonb('english_text').notNull(),
  germanText: jsonb('german_text').notNull(),
  privacy: jsonb('privacy'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
});

export const site_controls = pgTable(
  'site_controls',
  {
    id: serial('id').primaryKey(),
    sectionVisibility_showProjects: boolean('section_visibility_show_projects').default(true),
    sectionVisibility_showAbout: boolean('section_visibility_show_about').default(true),
    socials_linkedin: integer('socials_linkedin_id').references(() => tag.id, {
      onDelete: 'set null'
    }),
    socials_github: integer('socials_github_id').references(() => tag.id, {
      onDelete: 'set null'
    }),
    socials_mail: integer('socials_mail_id').references(() => tag.id, {
      onDelete: 'set null'
    }),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null'
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
  },
  (columns) => ({
    site_controls_socials_socials_linkedin_idx: index(
      'site_controls_socials_socials_linkedin_idx'
    ).on(columns.socials_linkedin),
    site_controls_socials_socials_github_idx: index('site_controls_socials_socials_github_idx').on(
      columns.socials_github
    ),
    site_controls_socials_socials_mail_idx: index('site_controls_socials_socials_mail_idx').on(
      columns.socials_mail
    ),
    site_controls_meta_meta_image_idx: index('site_controls_meta_meta_image_idx').on(
      columns.meta_image
    )
  })
);

export const relations_media = relations(media, () => ({}));
export const relations_users = relations(users, () => ({}));
export const relations_tag = relations(tag, () => ({}));
export const relations_experiences_rels = relations(experiences_rels, ({ one }) => ({
  parent: one(experiences, {
    fields: [experiences_rels.parent],
    references: [experiences.id],
    relationName: '_rels'
  }),
  tagID: one(tag, {
    fields: [experiences_rels.tagID],
    references: [tag.id],
    relationName: 'tag'
  })
}));
export const relations_experiences = relations(experiences, ({ many }) => ({
  _rels: many(experiences_rels, {
    relationName: '_rels'
  })
}));
export const relations_projects_rels = relations(projects_rels, ({ one }) => ({
  parent: one(projects, {
    fields: [projects_rels.parent],
    references: [projects.id],
    relationName: '_rels'
  }),
  tagID: one(tag, {
    fields: [projects_rels.tagID],
    references: [tag.id],
    relationName: 'tag'
  })
}));
export const relations_projects = relations(projects, ({ one, many }) => ({
  heroImage: one(media, {
    fields: [projects.heroImage],
    references: [media.id],
    relationName: 'heroImage'
  }),
  meta_image: one(media, {
    fields: [projects.meta_image],
    references: [media.id],
    relationName: 'meta_image'
  }),
  _rels: many(projects_rels, {
    relationName: '_rels'
  })
}));
export const relations__projects_v_rels = relations(_projects_v_rels, ({ one }) => ({
  parent: one(_projects_v, {
    fields: [_projects_v_rels.parent],
    references: [_projects_v.id],
    relationName: '_rels'
  }),
  tagID: one(tag, {
    fields: [_projects_v_rels.tagID],
    references: [tag.id],
    relationName: 'tag'
  })
}));
export const relations__projects_v = relations(_projects_v, ({ one, many }) => ({
  parent: one(projects, {
    fields: [_projects_v.parent],
    references: [projects.id],
    relationName: 'parent'
  }),
  version_heroImage: one(media, {
    fields: [_projects_v.version_heroImage],
    references: [media.id],
    relationName: 'version_heroImage'
  }),
  version_meta_image: one(media, {
    fields: [_projects_v.version_meta_image],
    references: [media.id],
    relationName: 'version_meta_image'
  }),
  _rels: many(_projects_v_rels, {
    relationName: '_rels'
  })
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels'
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media'
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users'
    }),
    tagID: one(tag, {
      fields: [payload_locked_documents_rels.tagID],
      references: [tag.id],
      relationName: 'tag'
    }),
    experiencesID: one(experiences, {
      fields: [payload_locked_documents_rels.experiencesID],
      references: [experiences.id],
      relationName: 'experiences'
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: 'projects'
    })
  })
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels'
    })
  })
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels'
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users'
    })
  })
);
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels'
  })
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));
export const relations_section_content_quick_skills = relations(
  section_content_quick_skills,
  ({ one }) => ({
    _parentID: one(section_content, {
      fields: [section_content_quick_skills._parentID],
      references: [section_content.id],
      relationName: 'quickSkills'
    })
  })
);
export const relations_section_content_rels = relations(section_content_rels, ({ one }) => ({
  parent: one(section_content, {
    fields: [section_content_rels.parent],
    references: [section_content.id],
    relationName: '_rels'
  }),
  tagID: one(tag, {
    fields: [section_content_rels.tagID],
    references: [tag.id],
    relationName: 'tag'
  })
}));
export const relations_section_content = relations(section_content, ({ one, many }) => ({
  avatar: one(media, {
    fields: [section_content.avatar],
    references: [media.id],
    relationName: 'avatar'
  }),
  selectedProjects: one(projects, {
    fields: [section_content.selectedProjects],
    references: [projects.id],
    relationName: 'selectedProjects'
  }),
  selectedExperiences: one(experiences, {
    fields: [section_content.selectedExperiences],
    references: [experiences.id],
    relationName: 'selectedExperiences'
  }),
  quickSkills: many(section_content_quick_skills, {
    relationName: 'quickSkills'
  }),
  _rels: many(section_content_rels, {
    relationName: '_rels'
  })
}));
export const relations_legal_content = relations(legal_content, () => ({}));
export const relations_site_controls = relations(site_controls, ({ one }) => ({
  socials_linkedin: one(tag, {
    fields: [site_controls.socials_linkedin],
    references: [tag.id],
    relationName: 'socials_linkedin'
  }),
  socials_github: one(tag, {
    fields: [site_controls.socials_github],
    references: [tag.id],
    relationName: 'socials_github'
  }),
  socials_mail: one(tag, {
    fields: [site_controls.socials_mail],
    references: [tag.id],
    relationName: 'socials_mail'
  }),
  meta_image: one(media, {
    fields: [site_controls.meta_image],
    references: [media.id],
    relationName: 'meta_image'
  })
}));

type DatabaseSchema = {
  enum_tag_type: typeof enum_tag_type;
  enum_projects_status: typeof enum_projects_status;
  enum__projects_v_version_status: typeof enum__projects_v_version_status;
  media: typeof media;
  users: typeof users;
  tag: typeof tag;
  experiences: typeof experiences;
  experiences_rels: typeof experiences_rels;
  projects: typeof projects;
  projects_rels: typeof projects_rels;
  _projects_v: typeof _projects_v;
  _projects_v_rels: typeof _projects_v_rels;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  section_content_quick_skills: typeof section_content_quick_skills;
  section_content: typeof section_content;
  section_content_rels: typeof section_content_rels;
  legal_content: typeof legal_content;
  site_controls: typeof site_controls;
  relations_media: typeof relations_media;
  relations_users: typeof relations_users;
  relations_tag: typeof relations_tag;
  relations_experiences_rels: typeof relations_experiences_rels;
  relations_experiences: typeof relations_experiences;
  relations_projects_rels: typeof relations_projects_rels;
  relations_projects: typeof relations_projects;
  relations__projects_v_rels: typeof relations__projects_v_rels;
  relations__projects_v: typeof relations__projects_v;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_section_content_quick_skills: typeof relations_section_content_quick_skills;
  relations_section_content_rels: typeof relations_section_content_rels;
  relations_section_content: typeof relations_section_content;
  relations_legal_content: typeof relations_legal_content;
  relations_site_controls: typeof relations_site_controls;
};

declare module '@payloadcms/db-postgres/types' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
